spring:
    profiles:
        active: dev
---
# 服务配置
server:
  port: 8001
# 数据库配置
spring:
  profiles: dev
  application:
    name: spring-cloud-provider-dept-dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root

# mybatis配置
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/DeptMapper.xml
  type-aliases-package: com.liang.springcloud.pojo
# Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: spring-cloud-8001-provider-hystrix # 修改默认eureka上描述默认信息
    hostname: localhost
info:
  app.name: XiaoLiang
  app.company: Zhou
---
# 服务配置
server:
  port: 8001
# 数据库配置
spring:
  profiles: test
  application:
    name: spring-cloud-provider-dept-test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root

# mybatis配置
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/DeptMapper.xml
  type-aliases-package: com.liang.springcloud.pojo
# Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: spring-cloud-8001-provider-hystrix # 修改默认eureka上描述默认信息
    hostname: localhost
info:
  app.name: XiaoLiang
  app.company: Zhou
